services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../DB_with_embeddings.sql:/tmp/DB_with_embeddings.sql
      - ./db_restore.sh:/docker-entrypoint-initdb.d/99_restore.sh
    environment:
      - POSTGRES_DB=pa2db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: rag_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pa2db"]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    container_name: ollama_rag
    entrypoint: /bin/bash /entrypoint.sh
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: