version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    container_name: ollama_rag
    entrypoint: /bin/bash /entrypoint.sh
    restart: unless-stopped