name: web-scraper
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crawldb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres -d crawldb"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"

  client:
    build: ./client
    depends_on:
      - server
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:example@db:5432/crawldb
      URL_SEED: https://www.24ur.com/
      MAX_PAGES: 5100
      WORKER_COUNT: 4
      QUERY: "Vojna med Ukrajino in Rusijo"
    ports:
      - "5001:5000"
    volumes:
      - ./client_output:/client/output

  server:
    build: ./server
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:example@db:5432/crawldb
    ports:
      - "5002:5000"

volumes:
  db_data:
