FROM pgvector/pgvector:pg17

USER root

RUN mkdir -p /var/lib/apt/lists/partial && \
    apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

COPY ./implementation-extraction/migration/database_restore.sh /docker-entrypoint-initdb.d/database_restore.sh

RUN chmod +x /docker-entrypoint-initdb.d/database_restore.sh

USER postgres